TODO/config/routes.rb
TODO::Application.routes.draw do
  resources :todos

  root :to => "todos#index"

end

TODO/app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :title
end

TODO/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

TODO/app/controllers/todos_controller.rb
class TodosController < ApplicationController

  respond_to :html, :xml, :js

  def index
    respond_with(@list = Todo.all)
  end

  def new
    @list = Todo.new
  end  

  def create
    @list = Todo.new(params[:todo])
    if @list.save
      redirect_to todo_url(@list)
    else
      redirect_to new_todo_url
    end
  end

  def show
    @list = Todo.find(params[:id])
  end

  def edit
    @list = Todo.find(params[:id])
  end

  def destroy
    @list = Todo.find(params[:id])
    if @list.destroy
      redirect_to todos_url
    else
      redirect_to todos_url
    end
  end
  
  def update
    @list = Todo.find(params[:id])
    if @list.update_attributes(params[:todo])
      redirect_to todo_path(@list)
    else 
      redirect_to edit_todo_path(@list)
    end
  end
end

TODO/app/helpers/application_helper.rb
module ApplicationHelper
end

TODO/app/helpers/todos_helper.rb
module TodosHelper
end

TODO/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TODO</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

TODO/app/views/todos/_form.html.erb
<%= form_for @list do |f| %>
<p><%= f.text_field :title %></p>
<p><%= f.submit "Edit" %></p>
<% end %>

TODO/app/views/todos/edit.html.erb
<h1>Edit todo entry</h1>
<%= render :partial => "form"%>

TODO/app/views/todos/index.html.erb
<h1> TODO List </h1>

<% @list.each do |l| %>
    <p style="color: red">
    <%=l.title%> 
    </p>
    <%= link_to "Edit todo", edit_todo_url(l) %> |   
    <%= link_to "Delete todo", todo_url(l), :method => :delete %>

<% end %>

<br>

<%= link_to "Add entry", new_todo_url %>

TODO/app/views/todos/new.html.erb
<h1> New ToDo list </h1>

<%= form_for @list do |f| %>
<p><%= f.text_field :title %></p>
<p><%= f.submit "Add" %></p>
<% end %>

TODO/app/views/todos/show.html.erb
<h1><%=@list.title%></h1>